theme: osuny
_merge: deep
enableRobotsTXT: true
removePathAccents: true
pagination:
  pagerSize: 30
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
  organizations:
    index:
      taxonomies:
        display: false
  # COMPONENTS
  components:
    lightbox:
      in_hero:
        disabled: true